### ISSUE TITLE
StreamingSubscriptionConnection.IsOpen incorrectly reporting status

### ISSUE THREAD

**Issue by axelitus** [OfficeDev/ews-managed-api#8] opened 2014-10-08 22:22 UTC
I'm building a Library to handle Streaming Subscriptions at https://bitbucket.org/axelitus/axelitus.kvasir

I'm doing some tests and when the Connection disconnects (due to reaching the lifetime limit) I re-open the connection but after that the IsOpen method returns false everytime even though I'm able to receive notifications through the subscription and the connection keeps disconnecting (when reaching the lifetime limit).

For the test I have a console application that loads a StreamListener that has a connection with lifetime set to 1 minute. I have a timer that asks for the connection status every 10 seconds. The StreamingSubscriptionConnection has a StreamConnection wrapper class that handles the automatic reconnection when timed out.

![connection](https://cloud.githubusercontent.com/assets/732441/4568376/96bd8b98-4f39-11e4-930f-d3c0fb7109fb.jpg)

**Comment by dclaux** [comment] 2015-04-17 19:18
Hi there,
Sorry for the long, long delay. I'm looking at the code and I can't quite figure out how it's even possible for IsOpen to be false when the subscription is open. For as long as you re-open the connection with StreamingSubscriptionConnection.Open, the code path always leads to IsOpen to be equal to true. Can you still repro this issue?

**Comment by axelitus** [comment] 2015-04-20 18:14
Hi... I could reproduce this behavior with the current code base.
![streamlistenertest](https://cloud.githubusercontent.com/assets/732441/7236723/4bc86ee4-e75c-11e4-9723-d8abbc0f80d1.jpg)
On the picture you can see that while the program reports that the connection is not opened, the NewEmail event is correctly received.

Here is the sample code (Command Line Application) to use the StreamListener wrapper for testing:
```
using Axelitus.Kvasir.Exchange;
using Axelitus.Kvasir.Security;
using Microsoft.Exchange.WebServices.Data;
using System;
using System.Timers;

namespace TestSpace
{
    internal class Program
    {
        private static StreamListener sl;
        private static string EWS_URL = @"";
        private static string MAILBOX_USERNAME = @"";
        private static string MAILBOX_PASSWORD = @"";

        private static void Main(string[] args)
        {
            // Setup a timer
            Timer tmr = new Timer(10000);
            tmr.Elapsed += tmr_Elapsed;
            // Manually setup the StreamListener
            sl = new StreamListener(ExchangeVersion.Exchange2010_SP2,
                EWS_URL, new SecureCredentials(MAILBOX_USERNAME, MAILBOX_PASSWORD));
            // Manually setup StreamConnection
            sl.StreamConnection = new StreamConnection(sl.Service, 1, true, true);
            sl.StreamConnection.ItemPropertyBindings.Add(SerializablePropertyDefinition.Subject);
            // Manually setup a subscription
            StreamSubscription s = new StreamSubscription(new FolderId(WellKnownFolderName.Inbox), EventType.NewMail);
            s.Subscribe(sl.Service);
            sl.StreamConnection.AddSubscription(s);
            // Register the StreamListener events
            sl.Connected += sl_Connected;
            sl.Disconnected += sl_Disconnected;
            sl.NewEmail += sl_NewEmail;
            Console.WriteLine(String.Format("Finished setting the StreamListener. Ready to start."));
            Console.WriteLine(String.Format("{0} - StreamListener Started. Connection Lifetime: 1 minute.", DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")));
            // Start the StreamListener and the Timer
            sl.Start();
            tmr.Start();
            // Infinite loop to see what's happening
            while (true)
            {
                if (Console.ReadKey().Key == ConsoleKey.Escape)
                {
                    break;
                }
            }

            tmr.Stop();
        }
        // Triggered when a new email arrives to the subscribed email and folder.
        static void sl_NewEmail(object sender, StreamNotificationEmailEventArgs e)
        {
            Console.WriteLine(String.Format("{0} - StreamListener NewEmail. Subject: {1}.", DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"), e.Email.Subject));
        }
        // Triggered when the StreamListener gets disconnected (usually when lifetime is reached).
        static void sl_Disconnected(object sender, StreamConnectionEventArgs e)
        {
            Console.WriteLine(String.Format("{0} - StreamListener Disconnected.", DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")));
        }
        // Triggered when the StreamListener gets connected (usually after disconnected and with autoReconnect set to true).
        static void sl_Connected(object sender, StreamConnectionEventArgs e)
        {
            Console.WriteLine(String.Format("{0} - StreamListener Connected.", DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")));
        }
        // Triggered when the laps time of the timer is reached.
        static void tmr_Elapsed(object sender, ElapsedEventArgs e)
        {
            Console.WriteLine(String.Format("{0} - StreamListener.StreamConnection.IsOpen: {1}.", DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"), sl.StreamConnection.IsOpen));
        }
    }
}
```

Just change ```EWS_URL```, ```MAILBOX_USERNAME```, ```MAILBOX_PASSWORD``` for the correct values of a server you can test.

**Comment by dclaux** [comment] 2015-04-20 20:38
I've looked at this again, but I really can't find a code path where StreamingSubscriptionConnection.IsOpen would be false as long as it is opened with Open. Your framework adds quite a bit of code on top of the EWS Managed API; at this point we'd need a repro that solely relies on the EWS Managed API. Could you provide that?

**Comment by axelitus** [comment] 2015-04-20 20:40
I'll write a code that "simulates" what the wrapper does (auto-reconnect and so on...)

Yes the code adds a bunch of thing as I want to be able to configure and auto-load streaming connection and subscriptions through XML as I am building a services HUB that uses email to receive instructions.

**Comment by dclaux** [comment] 2015-04-20 21:01
I was actually able to repro the issue without your library. Thanks for reporting, I'll investigate further.

**Comment by axelitus** [comment] 2015-04-20 21:09
Alright then! I was wondering if my framework introduced some strange thing there because of the asynchronicity (does that word exist? haha) of using events to propagate things around (though I was almost certain that shouldn't be the case).

If you need me to do anything to fix this just ask! ;) thanks.

**Comment by dclaux** [comment] 2015-04-20 22:12
Bug is in ```StreamingSubscriptionConnection.InternalOnDisconnect``` which sets ```this.currentHangingRequest = null``` *after* calling ```OnDisconnect```. That makes it impossible to reconnect in an ```OnDisconnect``` event handler.

Setting ```this.currentHangingRequest``` to null before calling ```OnDisconnect``` solves the problem:

```
        /// <summary>
        /// Internal helper method called when the request disconnects.
        /// </summary>
        /// <param name="ex">The exception that caused the disconnection. May be null.</param>
        private void InternalOnDisconnect(Exception ex)
        {
            this.currentHangingRequest = null;

            if (this.OnDisconnect != null)
            {
                this.OnDisconnect(this, new SubscriptionErrorEventArgs(null, ex));
            }
        }
```

**Comment by axelitus** [comment] 2015-04-21 13:36
I can confirm with my test that this does solve the issue at hand:
![ssc_status_fix](https://cloud.githubusercontent.com/assets/732441/7253298/379b2e8e-e801-11e4-8621-011799880702.jpg)

I'll be testing my Tray Notifier but I'm sure this is resolved with this little change of order. Thanks!

**Comment by dclaux** [comment] 2015-04-27 00:52
This is now fixed: https://github.com/OfficeDev/ews-managed-api/pull/40

**Closed by dclaux** 2015-04-27 00:52 UTC
Labels: bug

**Comment by rojobo** [comment] 2016-03-31 13:41
I'm able to reproduce this error using Managed API v.2.2 please reopen

**Comment by ethan-deng** [comment] 2017-02-09 19:20
When calling "open" on the connection without checking IsOpen, sometime it will throw this error.

The connection has already opened. at Microsoft.Exchange.WebServices.Data.StreamingSubscriptionConnection.ValidateConnectionState(Boolean isConnectedExpected, String errorMessage) in \REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Notifications\StreamingSubscriptionConnection.cs:line 287
at Microsoft.Exchange.WebServices.Data.StreamingSubscriptionConnection.Open() in \REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Notifications\StreamingSubscriptionConnection.cs:line 198

However if do check "IsOpen" and it returns true after disconnected what to do?

**Comment by naru1790** [comment] 2017-10-21 08:07
I am also facing the same issue in EWS managed api 2.2. please reopen it again
![test](https://user-images.githubusercontent.com/17177355/31849731-f91e0e80-b664-11e7-99bb-e26df5d5feef.png)

**Comment by naru1790** [comment] 2017-10-21 08:11
After debugging i have found out. On Disconnect event i get the connection IsOpen = false and currentHangingRequest = null. When i open the connection through connection.Open method for 1seconds connection remains open after that currenHangingRequest is set to null internally which in turn sets the IsOpen to false. Please fix this issue because it is creating issues with whole reconnection logic as well as creating problems with the connection stablity.
