### ISSUE TITLE
TimeZoneConversionException when converting time from new russian timezone (UTC+03:00) Moscow, St. Petersburg, Volgograd (RTZ 2) to UTC

### ISSUE THREAD

**Issue by streamstr** [OfficeDev/ews-managed-api#13] opened 2014-10-27 06:18 UTC
We developed a program, which works with Exchange Server appointments through EWS Managed API. It was working fine untill we installed recent windows update KB2998527, which is associated with time zone changes in Russia. Now when program attempts to create appointment in Exchange, EWS throws such exception:

Microsoft.Exchange.WebServices.Data.TimeZoneConversionException: Unable to convert 2014-01-01T00:00:00.000 from (UTC+03:00) Moscow, St. Petersburg, Volgograd (RTZ 2) to UTC. ---> System.ArgumentException: The supplied DateTime represents an invalid time.  For example, when the clock is adjusted forward, any time in the period that is skipped is invalid.
 Parameter name: dateTime
    at System.TimeZoneInfo.ConvertTime(DateTime dateTime, TimeZoneInfo sourceTimeZone, TimeZoneInfo destinationTimeZone, TimeZoneInfoOptions flags, CachedData cachedData)
    at Microsoft.Exchange.WebServices.Data.EwsUtilities.ConvertTime(DateTime dateTime, TimeZoneInfo sourceTimeZone, TimeZoneInfo destinationTimeZone)
    --- End of inner exception stack trace ---
    at Microsoft.Exchange.WebServices.Data.EwsUtilities.ConvertTime(DateTime dateTime, TimeZoneInfo sourceTimeZone, TimeZoneInfo destinationTimeZone)
    at Microsoft.Exchange.WebServices.Data.ExchangeServiceBase.ConvertDateTimeToUniversalDateTimeString(DateTime value)
    at Microsoft.Exchange.WebServices.Data.EwsServiceXmlWriter.TryConvertObjectToString(Object value, String& strValue)
    at Microsoft.Exchange.WebServices.Data.EwsServiceXmlWriter.WriteElementValue(XmlNamespace xmlNamespace, String localName, String displayName, Object value)
    at Microsoft.Exchange.WebServices.Data.EwsServiceXmlWriter.WriteElementValue(XmlNamespace xmlNamespace, String localName, Object value)
    at Microsoft.Exchange.WebServices.Data.AbsoluteDateTransition.WriteElementsToXml(EwsServiceXmlWriter writer)
    at Microsoft.Exchange.WebServices.Data.ComplexProperty.WriteToXml(EwsServiceXmlWriter writer, XmlNamespace xmlNamespace, String xmlElementName)
    at Microsoft.Exchange.WebServices.Data.TimeZoneDefinition.WriteElementsToXml(EwsServiceXmlWriter writer)
    at Microsoft.Exchange.WebServices.Data.ComplexProperty.WriteToXml(EwsServiceXmlWriter writer, XmlNamespace xmlNamespace, String xmlElementName)
    at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.WriteToXml(EwsServiceXmlWriter writer)
    at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.EmitRequest(IEwsHttpWebRequest request)
    at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.BuildEwsHttpWebRequest()
    at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.ValidateAndEmitRequest(IEwsHttpWebRequest& request)
    at Microsoft.Exchange.WebServices.Data.ExchangeService.InternalCreateItems(IEnumerable`1 items, FolderId parentFolderId, Nullable`1 messageDisposition, Nullable`1 sendInvitationsMode, ServiceErrorHandling errorHandling)
    at Microsoft.Exchange.WebServices.Data.Item.InternalCreate(FolderId parentFolderId, Nullable`1 messageDisposition, Nullable`1 sendInvitationsMode)
    at Microsoft.Exchange.WebServices.Data.Appointment.Save(WellKnownFolderName destinationFolderName, SendInvitationsMode sendInvitationsMode)

This exception is thrown if ExchangeService object is instantiated with one of time zones, which was changed. Here is display names and IDs of all Russian time zones and working state of each:   
(UTC+02:00) Kaliningrad (RTZ 1) -	Kaliningrad Standard Time - Not working
(UTC+03:00) Moscow, St. Petersburg, Volgograd (RTZ 2) - Russian Standard Time - Not working
(UTC+04:00) Izhevsk, Samara (RTZ 3) - Russia Time Zone 3 - Working
(UTC+05:00) Ekaterinburg (RTZ 4) - Ekaterinburg Standard Time - Not working
(UTC+06:00) Novosibirsk (RTZ 5) -	N. Central Asia Standard Time - Not working
(UTC+07:00) Krasnoyarsk (RTZ 6) - North Asia Standard Time - Not working
(UTC+08:00) Irkutsk (RTZ 7) -	North Asia East Standard Time - Not working
(UTC+09:00) Yakutsk (RTZ 8) - Yakutsk Standard Time - Not working
(UTC+10:00) Vladivostok, Magadan (RTZ 9) -	Vladivostok Standard Time - Not working
(UTC+11:00) Chokurdakh (RTZ 10)	 - Russia Time Zone 10 - Working
(UTC+12:00) Anadyr, Petropavlovsk-Kamchatsky (RTZ 11) - Russia Time Zone 11 - Working

If we use different (non-Russian) time zone - everything is OK. Date of the appointment is not 2014-01-01T00:00:00.000.

**Comment by dclaux** [comment] 2015-04-21 23:56
Sorry for the very long delay on this. I have a couple questions:
- Can it still be reproduced?
- I have a strong feeling that the problem comes from .NET's TimeZoneInfo parsing logic, not from the EWS Managed API. Could you try and repro without the EWS Managed API?

**Comment by BootGenius** [comment] 2015-04-25 11:17
No this problem is defenitely reproduced when you set up Moscow, St. Petersburg, Volgograd (RTZ 2) timezone. But the workaround described above works fine

**Comment by valeri2** [comment] 2015-05-07 09:01
Most likely the problem is in .NET's TimeZoneInfo parsing logic.
https://connect.microsoft.com/VisualStudio/feedback/details/1027179/timezone-conversion-bug
Bug is marked as fixed, but on my system the problem is reproduced.

**Comment by dclaux** [comment] 2015-05-13 00:25
I suspect the issue in the .NET framework has indeed been fixed but the updated framework hasn't shipped yet.
Closing this bug as it is not an EWS API issue.

**Closed by dclaux** 2015-05-13 00:25 UTC
Labels: bug

**Comment by tlecomte** [comment] 2016-08-05 12:54
We've just had the same error with up-to-date .NET framework, more than a year later, when loading an email attachment with `itemAttachment.Load(ItemSchema.MimeContent)`. Any suggestion?

```
Microsoft.Exchange.WebServices.Data.TimeZoneConversionException: Unable to convert 2009-01-01T00:00:00.000 from (UTC-03:00) City of Buenos Aires to UTC.
---> System.ArgumentException: The supplied DateTime represents an invalid time.  For example, when the clock is adjusted forward, any time in the period that is skipped is invalid.
Parameter name: dateTime
   at System.TimeZoneInfo.ConvertTime(DateTime dateTime, TimeZoneInfo sourceTimeZone, TimeZoneInfo destinationTimeZone, TimeZoneInfoOptions flags, CachedData cachedData)
   at Microsoft.Exchange.WebServices.Data.EwsUtilities.ConvertTime(DateTime dateTime, TimeZoneInfo sourceTimeZone, TimeZoneInfo destinationTimeZone) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\EwsUtilities.cs:line 713
--- End of inner exception stack trace ---
   at Microsoft.Exchange.WebServices.Data.EwsUtilities.ConvertTime(DateTime dateTime, TimeZoneInfo sourceTimeZone, TimeZoneInfo destinationTimeZone) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\EwsUtilities.cs:line 720
   at Microsoft.Exchange.WebServices.Data.ExchangeServiceBase.ConvertDateTimeToUniversalDateTimeString(DateTime value) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\ExchangeServiceBase.cs:line 424
   at Microsoft.Exchange.WebServices.Data.EwsServiceXmlWriter.TryConvertObjectToString(Object value, String& strValue) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\EwsServiceXmlWriter.cs:line 66
   at Microsoft.Exchange.WebServices.Data.EwsServiceXmlWriter.WriteElementValue(XmlNamespace xmlNamespace, String localName, String displayName, Object value) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\EwsServiceXmlWriter.cs:line 316
   at Microsoft.Exchange.WebServices.Data.AbsoluteDateTransition.WriteElementsToXml(EwsServiceXmlWriter writer) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\ComplexProperties\TimeZones\AbsoluteDateTransition.cs:line 73
   at Microsoft.Exchange.WebServices.Data.ComplexProperty.WriteToXml(EwsServiceXmlWriter writer, XmlNamespace xmlNamespace, String xmlElementName) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\ComplexProperties\ComplexProperty.cs:line 272
   at Microsoft.Exchange.WebServices.Data.ComplexProperty.WriteToXml(EwsServiceXmlWriter writer, String xmlElementName) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\ComplexProperties\ComplexProperty.cs:line 283
   at Microsoft.Exchange.WebServices.Data.TimeZoneDefinition.WriteElementsToXml(EwsServiceXmlWriter writer) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\ComplexProperties\TimeZones\TimeZoneDefinition.cs:line 403
   at Microsoft.Exchange.WebServices.Data.ComplexProperty.WriteToXml(EwsServiceXmlWriter writer, XmlNamespace xmlNamespace, String xmlElementName) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\ComplexProperties\ComplexProperty.cs:line 272
   at Microsoft.Exchange.WebServices.Data.ComplexProperty.WriteToXml(EwsServiceXmlWriter writer, String xmlElementName) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\ComplexProperties\ComplexProperty.cs:line 283
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.WriteToXml(EwsServiceXmlWriter writer) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\Requests\ServiceRequestBase.cs:line 251
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.EmitRequest(IEwsHttpWebRequest request) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\Requests\ServiceRequestBase.cs:line 419
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.BuildEwsHttpWebRequest() in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\Requests\ServiceRequestBase.cs:line 790
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.ValidateAndEmitRequest(IEwsHttpWebRequest& request) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\Requests\ServiceRequestBase.cs:line 687
   at Microsoft.Exchange.WebServices.Data.MultiResponseServiceRequest`1.Execute() in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\Requests\MultiResponseServiceRequest.cs:line 157
   at Microsoft.Exchange.WebServices.Data.ExchangeService.InternalGetAttachments(IEnumerable`1 attachments, Nullable`1 bodyType, IEnumerable`1 additionalProperties, ServiceErrorHandling errorHandling) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\ExchangeService.cs:line 1469
   at Microsoft.Exchange.WebServices.Data.ItemAttachment.Load(PropertyDefinitionBase[] additionalProperties) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\ComplexProperties\ItemAttachment.cs:line 215```

**Comment by trannann** [comment] 2017-04-11 17:39
Running on updated WIN10 and .NET framework 4.6.2, VS 2015 - still having this issue with Russian Standard Time. 

thats how I create an appointment:

```
TimeZoneInfo tzi = TimeZoneInfo.FindSystemTimeZoneById("Russian Standard Time");

var appointment = new Appointment(service)
{
        // Set properties on the appointment.
        ICalUid = calendarEvent.EventId.ICalUid,
	Subject = calendarEvent.Subject,
	Start = calendarEvent.StartUtc.ToUniversalTime(),
	End = calendarEvent.EndUtc.ToUniversalTime(),
	Location = GetLocationsDescription(calendarEvent),
	Body = this.BodyHtmlText(calendarEvent),
	StartTimeZone = tzi,
	EndTimeZone = tzi
};
```

Exception:

```
Microsoft.Exchange.WebServices.Data.ServiceResponseException: The specified time zone isn't valid.
   at Microsoft.Exchange.WebServices.Data.ServiceResponse.InternalThrowIfNecessary()
   at Microsoft.Exchange.WebServices.Data.ExchangeService.InternalCreateItems(IEnumerable`1 items, FolderId parentFolderId, Nullable`1 messageDisposition, Nullable`1 sendInvitationsMode, ServiceErrorHandling errorHandling)
   at Microsoft.Exchange.WebServices.Data.Item.InternalCreate(FolderId parentFolderId, Nullable`1 messageDisposition, Nullable`1 sendInvitationsMode)
   at Microsoft.Exchange.WebServices.Data.Appointment.Save(SendInvitationsMode sendInvitationsMode)
   at BookingSystem.Exchange.ExchangeGateway.InsertEvent(ExchangeService service, String targetAddress, Appointment appointment)
   at BookingSystem.Exchange.ExchangeGateway.CreateCalendarEvent(CalendarEvent calendarEvent)
   at BookingSystem.Exchange.ExchangeGateway.SendCalendar(CalendarEventMethodType methodType, CalendarEvent calendarEvent)
   at MeetingScheduler.MeetingSchedulerTasks.ReserveMeeting(DateTime startUtc, DateTime endUtc, Int32 organiserId, Nullable`1 onBehalfOfId, Int32[] personIds, String[] personEmails, Int32[] meetingRoomIds, String subject, String body)
   at Web.Controllers.HomeController.ReserveMeetingRooms(String subject, String body, DateTime start, DateTime end, Nullable`1 onBehalfOfId, Int32[] personIds, String[] personEmails, Int32[] meetingRoomIds)
```

as you can see its clearly triggered in the EWS API method Appointment.Save()

**Comment by michalhainc** [comment] 2018-01-23 13:52
I'm still facing the issue, so you are telling me that fixed .net hasnt been shipped yet (3 years after?). Doubt.

**Comment by wild0ne** [comment] 2018-11-29 08:25
This worked for me, thanks to @BootGenius . Now I always create appointments with custom TimeZone.

```
TimeZoneInfo.CreateCustomTimeZone("Time zone to workaround a bug",
TimeZoneInfo.Local.BaseUtcOffset,
"Time zone to workaround a bug",
"Time zone to workaround a bug")
```
