### ISSUE TITLE
bug - ews throws an exception when the http headers contain the same key twice

### ISSUE THREAD

**Issue by robert-io** [OfficeDev/ews-managed-api#45] opened 2015-06-15 13:11 UTC
i have found i get an exception from time to time originating from the "Microsoft.Exchange.WebServices.Data.ExchangeServiceBase.SaveHttpResponseHeaders" method.  After examining some HTTP responses using fiddler and the code in that method i'm quite certain that the logic is flawed.

The only example i have come across (i'm not saying its the only one) is the "Set-Cookie" header, in some responses from exchange there are two of them.  As the method loops through the keys and add's them to the dictionary without checking for there existence the dictionary throws an exception.
```c#
private void SaveHttpResponseHeaders(WebHeaderCollection headers)
{
	this.httpResponseHeaders.Clear();

	foreach (string key in headers.AllKeys)
	{
		this.httpResponseHeaders.Add(key, headers[key]);
	}

	if (this.OnResponseHeadersCaptured != null)
	{
		this.OnResponseHeadersCaptured(headers);
	}
}
```
I would suggest either filtering out duplicates with a:
```c#
if(!this.httpResponseHeaders.ContainsKey(key)) {
    this.httpResponseHeaders.Add(key, headers[key]);
}
```
or handle specific cases as you encounter them.  For the "Set-Cookie" case you might want to drop the expires and path data so that the "Set-Cookie" value looks like the document.cookie in a browser.
```c#
private void SaveHttpResponseHeaders(WebHeaderCollection headers)
{
	this.httpResponseHeaders.Clear();

	foreach (string key in headers.AllKeys)
	{
		switch(key)
		{
			case "Set-Cookie":
				if(this.httpResponseHeaders.ContainsKey(key)) {
					this.httpResponseHeaders[key] += StripCookie(headers[key]);
				}
				else {
					this.httpResponseHeaders.Add(key, StripCookie(headers[key]));
				}
				break;

			default:
				this.httpResponseHeaders.Add(key, headers[key]);
				break;
		}
	}

	if (this.OnResponseHeadersCaptured != null)
	{
		this.OnResponseHeadersCaptured(headers);
	}
}

private string StripCookie(string cookie)
{
	var end_of_cookie = cookie.IndexOf(';');
	
	if (end_of_cookie == -1) {
		end_of_cookie = cookie.Length;
	}
	
	return string.Concat(cookie.Substring(0, end_of_cookie), ";");
}
```

**Comment by dclaux** [comment] 2015-06-15 16:20
Hi there, thanks for reporting. This is indeed a bug. However I believe the right fix is to use a NameValueCollection rather than a Dictionary for HttpResponseHeaders, although it could be a breaking change for some apps.

**Comment by cklam2** [comment] 2015-07-30 11:49
We've also seen this exception being thrown in SaveHttpResponseHeaders so hope there will be a fix soon.

What I don't understand is why the exception occurs. The WebHeaderCollection is derived from NameValueCollection. This class doesn't store duplicate keys. When you call Add multiple times with the same key the values are added to the existing one, separating them by a comma.
 
```
headers.Add(HttpResponseHeader.SetCookie, "SomeValue");
headers.Add("Set-Cookie", "OtherValue");
headers.Add("set-cookie", "MoreValue");
headers.Add("Set-Cookie:LastValue");
```
will result in just 1 entry (and headers.AllKeys only returns 1 key):
```"Set-Cookie": "SomeValue,OtherValue,MoreValue,LastValue"```

So theoretically there won't be duplicate keys. Am I missing something?

**Comment by robert-io** [comment] 2015-07-31 07:21
@cklam2 they are adding the headers to a Dictionary<string, string> and thats what caused the issue.

The following file and line numbers are correct at time of writing (08:15 31 July 2015 GMT):
 * https://github.com/OfficeDev/ews-managed-api/blob/master/Core/ExchangeServiceBase.cs
   * Line 93 - Variable Declaration
   * Line 344 - Copies from WebHeaderCollection  to Dictionary<string, string> and causes the exception.

Note: I would add a link to the specific file revision if i knew how so the path to the latest one will have to do.

**Comment by cklam2** [comment] 2015-07-31 08:49
@robert-io I was indeed referring to that method, excerpt below:
```C#
private IDictionary<string, string> httpResponseHeaders = new Dictionary<string, string>();

private void SaveHttpResponseHeaders(WebHeaderCollection headers)
{
    this.httpResponseHeaders.Clear();

    foreach (string key in headers.AllKeys)
    {
        // Assuming that the exception was thrown from following line
        this.httpResponseHeaders.Add(key, headers[key]);
    }
    ...
}
```

Parameter ```headers``` is a [WebHeaderCollection](https://msdn.microsoft.com/en-us/library/system.net.webheadercollection.aspx). 

According to [MSDN](https://msdn.microsoft.com/en-us/library/y280s7kx.aspx) and the [source code](http://referencesource.microsoft.com/#System/net/System/Net/WebHeaderCollection.cs) (plus after trying to reproduce myself) the WebHeaderCollection will **not** create a new entry when the key already exists in the collection. Instead it will append value to the existing value, separating them with a comma.

So therefore the headers.AllKeys should never return duplicate values. And the httpResponseHeaders collection is also cleared before foreach is called.

My question is, since AllKeys only returns unique keys, why is this part of code still throwing an ArgumentException (An item with the same key has already been added.)?

Not arguing whether this is a bug (cause I've seen it happening), just trying to understand why it fails.

**Comment by dclaux** [comment] 2015-08-03 19:33
Good question, not sure why. A bug in .NET maybe? Or a documentation error?
Assuming the documentation is right, the fix to the API should be to implement the same behavior as the one documented for WebHeaderCollection. Do you want to give it a shot?

**Comment by dclaux** [comment] 2015-08-05 16:45
Hi there, I have a fix for this bug pending integration in this pull request: https://github.com/OfficeDev/ews-managed-api/pull/55
Feel free to take a look and let me know if it solves your issue before I merge.

**Comment by cklam2** [comment] 2015-08-06 09:01
Thanks for the fix. 

The exception does not occur frequently, might need more regression to make sure that exception will not be thrown anymore. 

I was only wondering, if the AllKeys doesn't return unique keys (bug, documentation error), what result will headers[key] yield the second time? Anyway, more a question for the .NET FW team.

**Comment by dclaux** [comment] 2015-08-06 23:48
Fixed with https://github.com/OfficeDev/ews-managed-api/pull/55

**Closed by dclaux** 2015-08-06 23:48 UTC
Labels: bug

**Comment by cklam2** [comment] 2016-11-15 13:18
Issue is not fixed with the committed solution. I added an investigation (see [here](https://github.com/OfficeDev/ews-managed-api/issues/88#issuecomment-260637426)) in another bug report that is still open (I can't reopen this one).

In short: the `this.httpResponseHeaders` seems to be accessed simultaneously by 2 or more threads so ArgumentExceptions are still thrown.

**Comment by cklam2** [comment] 2018-02-27 23:15
I know it's super late for a solution but Microsoft just stated (see #104) that this happens when you access the same EWS instance from multiple threads. Solution is to create an instance per thread.
